name: Конвертация исходников в формат конфигуратора
on:
  push:
    branches:
      - 'develop'
      - 'actions'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.number }}-export
  cancel-in-progress: true

jobs:
  build:
    name: Подготовка окружения
    runs-on: ubuntu-22.04

    steps:
     
    - name: Извлечение исходников ветки ${{ github.ref_name }}
      if: github.event_name == 'push'
      uses: actions/checkout@v4

    - name: Установка 1C:EDT
      uses: 1CDevFlow/onec-setup-action@main
      with:
        type: edt
        edt_version: 2024.1.3
        cache: true
      env:
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      timeout-minutes: 30

    - name: Установка 1С:Предприятие 8.3.14.1944
      uses: 1CDevFlow/onec-setup-action@main
      with:
        type: onec
        onec_version: 8.3.14.1944
        cache: true
      env: 
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      timeout-minutes: 10      

    - name: Setup Onescript Action
      uses: otymko/setup-onescript@v1.4
      with:
        # Version of Onescript to use. Support value: 1.3.0, 1.5.0, 1.8.1, dev
        version: 1.9.2
        # Version of Onescript manager to use. Support value: 1.1.0, 1.2.0, latest
        # ovm_version: # optional, default is latest
          
    - name: Ковертация исходников Инструментов
      run: oscript ${{ github.base_ref }}/build.sh
      timeout-minutes: 5

    # - name: Ковертация исходников Портативной обработки
    #   uses: alkoleft/onec-edtcli-command-action@main
    #   with:
    #     export: true
    #     from: src/Портативный
    #     to: export/Портативный
    #     timeout: 15
    #   timeout-minutes: 15

    # - name: Упаковка исходников в архив
    #   run: |
    #     cd export
    #     7za a -t7z ../export.7z ./

    # - name: Публикация исходников в формате конфигуратора
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: export.7z
        if-no-files-found: error
        retention-days: 1
