name: Конвертация исходников в формат конфигуратора
on:
  push:
    branches:
      - "develop"
      - "actions"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.number }}-export
  cancel-in-progress: true

jobs:
  export-xml:
    name: Экспорт исходников в формате конфигуратора
    runs-on: ubuntu-22.04
    env:
      TOOLS_UI_1C_BUILDER_EDT_PATH: "/opt/1C/1CE/components/1c-edt-2024.1.3+13-x86_64/"
    steps:
      - name: JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Извлечение исходников ветки ${{ github.ref_name }}
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Установка 1C:EDT
        uses: 1CDevFlow/onec-setup-action@main
        with:
          type: edt
          edt_version: 2024.1.3
          cache: true
        env:
          ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
          ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
        timeout-minutes: 30

      - name: Setup Onescript Action
        uses: otymko/setup-onescript@v1.4
        with:
          version: 1.8.4

      - name: Установка зависимостей Oscript
        run: opm install cli fs logos tempfiles v8runner v8find 1commands
        
      - name: Конвертация исходников
        run: oscript -encoding=utf-8 ./src/builder/build.os xml

      - name: Упаковка исходников в архив
        run: |
          cd build
          7za a -t7z ../export.7z ./source
          # rm -R source

      - name: Публикация исходников в формате конфигуратора
        uses: actions/upload-artifact@v4
        with:
          name: designer-src
          path: build/source
          if-no-files-found: error
          retention-days: 1

  build-github:
    name: Сборка файлов инструментов cfe/cf
    runs-on: ubuntu-20.04
    needs: export-xml
    env:
      TOOLS_UI_1C_BUILDER_PLATFORM_PATH: "/opt/1C/v8.3/x86_64/"

    steps:
      - name: Извлечение исходников ветки ${{ github.ref_name }}
        if: github.event_name == 'push'
        uses: actions/checkout@v4

      - name: Загрузка исходников в формате конфигуратора
        uses: actions/download-artifact@v4
        with:
          name: designer-src
          path: build/source
      
      # - name: Распаковка исходников
      #   run: |
      #     mkdir export
      #     cd export
      #     7z x ../export.7z -y

      - name: Установка 1С:Предприятие 8.3.17.2760
        uses: 1CDevFlow/onec-setup-action@main
        with:
          type: onec
          onec_version: 8.3.17.2760
          cache: true
        env:
          ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
          ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
        timeout-minutes: 10

      - name: Setup Onescript Action
        uses: otymko/setup-onescript@v1.4
        with:
          version: 1.8.4

      - name: Сборка расширений
        run: oscript -encoding=utf-8 src/builder/build.os cfe
        timeout-minutes: 30      
      - name: Сборка конфигураций
        run: oscript -encoding=utf-8 src/builder/build.os cfe
        timeout-minutes: 30

  #     # - name: Ковертация исходников Портативной обработки
  #     #   uses: alkoleft/onec-edtcli-command-action@main
  #     #   with:
  #     #     export: true
  #     #     from: src/Портативный
  #     #     to: build/source/Портативный
  #     #     timeout: 15
  #     #   timeout-minutes: 15

  #     - name: Упаковка исходников в архив
  #       run: |
  #         cd build
  #         rm -R source
  #         7za a -t7z ../export.7z ./

  #     - name: Публикация исходников в формате конфигуратора
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: export.7z
  #         path: export.7z
  #         if-no-files-found: error
  #         retention-days: 1
