name: Конвертация исходников в формат конфигуратора
on:
  push:
    branches:
      - "develop"
      - "actions"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.number }}-export
  cancel-in-progress: true

jobs:
  export-xml:
    name: Экспорт исходников в формате конфигуратора
    runs-on: ubuntu-22.04
    env:
      TOOLS_UI_1C_BUILDER_EDT_PATH: "/opt/1C/1CE/components/1c-edt-2024.1.3+13-x86_64/"
    steps:
      - name: Извлечение исходников ветки ${{ github.ref_name }}
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Установка 1C:EDT
        uses: 1CDevFlow/onec-setup-action@main
        with:
          type: edt
          edt_version: 2024.1.3
          cache: true
        env:
          ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
          ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
        timeout-minutes: 30

      - name: Setup Onescript Action
        uses: otymko/setup-onescript@v1.4
        with:
          version: 1.8.4

      - name: Установка зависимостей Oscript
        run: opm install cli fs logos tempfiles v8runner v8find 1commands
        
      - name: Конвертация исходников
        run: oscript -encoding=utf-8 ./src/builder/build.os xml

      - name: Публикация исходников в формате конфигуратора
        uses: actions/upload-artifact@v4
        with:
          name: designer-src
          path: build/source
          if-no-files-found: error
          retention-days: 1

  build-github:
    name: Сборка файлов инструментов cfe/cf
    runs-on: ubuntu-20.04
    needs: export-xml
    env:
      TOOLS_UI_1C_BUILDER_PLATFORM_PATH: "/opt/1C/v8.3/x86_64/"

    steps:
      - name: Извлечение исходников ветки ${{ github.ref_name }}
        if: github.event_name == 'push'
        uses: actions/checkout@v4

      - name: Загрузка исходников в формате конфигуратора
        uses: actions/download-artifact@v4
        with:
          name: designer-src
          path: build/source
      
      # - name: Распаковка исходников
      #   run: |
      #     mkdir export
      #     cd export
      #     7z x ../export.7z -y

      - name: Установка 1С:Предприятие 8.3.17.2760
        uses: 1CDevFlow/onec-setup-action@main
        with:
          type: onec
          onec_version: 8.3.17.2760
          cache: true
        env:
          ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
          ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
        timeout-minutes: 10

      - name: Setup Onescript Action
        uses: otymko/setup-onescript@v1.4
        with:
          version: 1.8.4

      - name: Сборка расширений
        run: oscript -encoding=utf-8 src/builder/build.os cfe
        timeout-minutes: 30    
        
      - name: Сборка конфигураций
        run: oscript -encoding=utf-8 src/builder/build.os cf
        timeout-minutes: 30
      - name: Публикация файлов
        uses: softprops/action-gh-release@v2
        if: ${{ success() }}
        with:
          prerelease: true
          files: |
            build/*.cfe
            build/*.cf
          fail_on_unmatched_files: true
          generate_release_notes: false
          tag_name: "nigth"
          append_body: false
          name: Ночная сборка по коммиту ${{ github.event.head_commit }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-portable:
    name: Сборка файлов портативной поставки
    runs-on: self-hosted
    needs: export-xml
    env:
      TOOLS_UI_1C_BUILDER_PLATFORM_PATH: "C:\\Program Files\\1cv8\\8.3.17.2256\\bin\\"

    steps:
      - name: Извлечение исходников ветки ${{ github.ref_name }}
        if: github.event_name == 'push'
        uses: actions/checkout@v4

      - name: Загрузка исходников в формате конфигуратора
        uses: actions/download-artifact@v4
        with:
          name: designer-src
          path: build/source
      
      - name: Сборка портативной
        run: oscript -encoding=utf-8 src/builder/build.os epf
        timeout-minutes: 30    
        
      - name: Публикация файлов
        uses: softprops/action-gh-release@v2
        if: ${{ success() }}
        with:
          prerelease: true
          files: build/*.epf
          fail_on_unmatched_files: true
          generate_release_notes: false
          tag_name: "nigth"
          append_body: false
          name: Ночная сборка по коммиту "${{ github.event.head_commit.message }}"
          token: ${{ secrets.GITHUB_TOKEN }}

  

  

