name: Конвертация исходников в формат конфигуратора
on:
  push:
    branches:
      - 'develop'
      - 'actions'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.number }}-export
  cancel-in-progress: true

jobs:
  build:
    name: Сборка файлов инструментов
    runs-on: ubuntu-20.04
    env:
      TOOLS_BUILDER_PLATFORM_PATH: "/opt/1C/v8.3/x86_64/"
      TOOLS_BUILDER_EDT_PATH: "/opt/1C/1CE/components/1c-edt-2024.1.3+13-x86_64/"

    steps:
     
    # - name: Извлечение исходников ветки ${{ github.ref_name }}
    #   if: github.event_name == 'push'
    #   uses: actions/checkout@v4

    - name: Установка 1C:EDT
      uses: 1CDevFlow/onec-setup-action@main
      with:
        type: edt
        edt_version: 2024.1.3
        cache: true
      env:
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      timeout-minutes: 30

    # - name: Установка 1С:Предприятие 8.3.14.2095
    #   uses: 1CDevFlow/onec-setup-action@main
    #   with:
    #     type: onec
    #     onec_version: 8.3.14.2095
    #     cache: true
    #   env: 
    #     ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
    #     ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
    #   timeout-minutes: 10     

    # - name: Setup Onescript Action
    #   uses: otymko/setup-onescript@v1.4
    #   with:
    #     version: 1.8.4

    # - name: Установка зависимостей Oscript
    #   run: opm install cli fs logos tempfiles v8runner v8find 1commands

    - name: Экспорт исходников
      shell: bash
      # run: cd ${{ github.workflow }} && oscript -encoding=utf-8 .\src\builder\build.os  --edtSource="C:\Program Files\1C\1CE\components\1c-edt-2024.1.3+13-x86_64\" --platformSource="C:\Program Files\1cv8\8.3.14.2095\bin\"
      # run: oscript.exe -encoding=utf-8 .\src\builder\build.os 
      run: ${{ env.TOOLS_BUILDER_EDT_PATH }}1cedtcli -v -data ${{ github.workflow }}/build/tmp/instrumdata -command export --project ${{ github.workflow }}/src/Инструменты --configuration-files ${{ github.workflow }}/build/source/Инструменты
      timeout-minutes: 30
      # working-directory: ${{ env.TOOLS_BUILDER_EDT_PATH }}

    # - name: Ковертация исходников Инструменты
    #   uses: alkoleft/onec-edtcli-command-action@main
    #   with:
    #     export: true
    #     from: src/Инструменты
    #     to: build/source/Инструменты
    #     timeout: 15
    #   timeout-minutes: 15  

    # - name: Ковертация исходников Портативный
    #   uses: alkoleft/onec-edtcli-command-action@main
    #   with:
    #     export: true
    #     from: src/Портативный
    #     to: build/source/Портативный
    #     timeout: 15
    #   timeout-minutes: 15  

    # - name: Каталог репозитория
    #   run: echo ${{ github.workflow }}

    - name: Файлы билда
      run: cd build && ls -aRl

    - name: Сборка расширений
      run: oscript -encoding=utf-8 .\src\builder\build.os --platformSource="C:\Program Files\1cv8\8.3.14.2095\bin"  --exportEDT=false --cfe=true --cf=false --epf=false --deleteSourse=false
      timeout-minutes: 30

    # - name: Ковертация исходников Портативной обработки
    #   uses: alkoleft/onec-edtcli-command-action@main
    #   with:
    #     export: true
    #     from: src/Портативный
    #     to: build/source/Портативный
    #     timeout: 15
    #   timeout-minutes: 15

    # - name: Упаковка исходников в архив
    #   run: |
    #     cd export
    #     7za a -t7z ../export.7z ./

    # - name: Публикация исходников в формате конфигуратора
      # uses: actions/upload-artifact@v4
      # with:
      #   name: ${{ inputs.artifact_name }}
      #   path: export.7z
      #   if-no-files-found: error
      #   retention-days: 1
